[package]
name = "rust_kernel"
version = "0.1.0"
authors = ["HinamoreCh4n <motherrussia711@gmail.com>"]
edition = "2018"

[package.metadata.bootimage]
run-command = ["qemu-system-x86_64", "-drive", "format=raw,file={}", "-s", "-vga", "std",
                "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-device",
                "rtl8139,netdev=u1", "-netdev", "user,id=u1", "-object", "filter-dump,id=f1,netdev=u1,file=dump.dat"]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"]
test-success-exit-code = 33 # (0x10 << 1) | 1
test-timeout = 300

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = { version = "0.8.3", features = ["map_physical_memory"] }
volatile = "0.2.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.5.2"
x86_64 = "0.8.1"
uart_16550 = "0.2.1"
pic8259_simple = { path = "../pic8259_simple" }
pc-keyboard = "0.5.0"
linked_list_allocator = "0.6.4"
menu = "0.3.2"
arraydeque = { version = "0.4.5", default-features = false }
x86 = "0.29.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[test]]
name = "stack_overflow"
harness = false
